<?php
return [
    [
        'key'   => 'erp',
        'name'  => 'erp::app.admin.system.erp-connector',
        'info'  => 'erp::app.admin.system.info',
        'sort'  => 1,
    ],
    [
        'key'   => 'erp.settings',
        'name'  => 'erp::app.admin.system.settings',
        'info'  => 'erp::app.admin.system.info',
        'sort'  => 1,
    ],
    [
        'key'    => 'erp.settings.general',
        'name'   => 'erp::app.admin.system.general',
        'info'   => 'erp::app.admin.system.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'          => 'backend_url',
                'title'         => 'erp::app.admin.system.backend-url',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'erp_token',
                'title'         => 'erp::app.admin.system.erp-token',
                'type'          => 'password',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'keycloak_token_url',
                'title'         => 'erp::app.admin.system.keycloak-token-url',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'keycloak_client_id',
                'title'         => 'erp::app.admin.system.keycloak-client-id',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'keycloak_client_secret',
                'title'         => 'erp::app.admin.system.keycloak-client-secret',
                'type'          => 'password',
                'validation'    => '',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'keycloak_username',
                'title'         => 'erp::app.admin.system.keycloak-username',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
            ],
            [
                'name'          => 'keycloak_password',
                'title'         => 'erp::app.admin.system.keycloak-password',
                'type'          => 'password',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
            ],   
            [
                'name'          => 'connection_test_button',
                'title'         => '',
                'type'          => 'blade',
                'path'          => 'erp::admin.connection-test-field',
            ],
             [
                'name'          => 'auto_sync_enabled',
                'title'         => 'Enable Auto Sync',
                'type'          => 'boolean',
                'channel_based' => true,
            ],
            [
                'name'          => 'auto_sync_interval',
                'title'         => 'Sync Interval (Hours)',
                'type'          => 'select',
                'options'       => [
                    ['title' => '1 Minute (Testing)', 'value' => 'test-1'],
                    ['title' => '2 Minutes (Testing)', 'value' => 'test-2'],
                    ['title' => 'Every Hour', 'value' => 1],
                    ['title' => 'Every 3 Hours', 'value' => 3],
                    ['title' => 'Every 6 Hours', 'value' => 6],
                    ['title' => 'Every 12 Hours', 'value' => 12],
                    ['title' => 'Daily (24 Hours)', 'value' => 24],
                ],
                'channel_based' => true,
            ],
        ]
    ]
];